- name: demo on vars
  hosts: localhost
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL_PLAY - {{ URL_PLAY }}
    - name: print tasks variables
      ansible.builtin.debug:
        msg: URL_TASK - {{ URL_TASK }}
      vars:
          URL_TASK: tasks.example.com





# play level variables can be access by all the tasks & roles
# tasks level variables only access by the tasks