- name: demo on vars
  hosts: localhost
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL_PLAY - {{ URL_PLAY }}
    - name: print tasks variables
      ansible.builtin.debug:
        msg: URL_TASKS - {{ URL_TASKS }}
        vars:
          URL_TASKS: tasks.example.com




# play level variables can be access by all the tasks & roles
# tasks level variables only access by the tasks